version: '3.9'

services:
  backend:
    build:
      context: ./backend
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: budget-backend1
    image: gowthamac/budget1:be-v1
    env_file:
      - ./backend/.env
    ports:
      - "8053:8053"
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               gunicorn config.wsgi:application --bind 0.0.0.0:8053 --workers 3 --reload"
    restart: unless-stopped

  frontend:
    image: gowthamac/budget1:fe-v1
    build:
      context: ./frontend
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: budget-frontend1
    env_file:
      - ./frontend/.env
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  static_volume:
  media_volume: